(function(global){
'use strict';
const TR=Object.freeze({K200_NIGHT_TRADE:'H0MFCNT0',K200_NIGHT_QUOTE:'H0MFASP0',KRX_TRADE:'H0STCNT0'});
function splitFrame(raw){const text=String(raw||'');const parts=text.split('|');if(parts.length<4)return {ok:false,error:'MALFORMED_FRAME',raw:text};const trId=String(parts[1]||'').trim();const dataCount=Number(parts[2]);const payload=parts.slice(3).join('|');if(!trId||!Number.isInteger(dataCount)||dataCount<0||!payload)return {ok:false,error:'MALFORMED_FRAME',raw:text};return {ok:true,trId,dataCount,payload,fields:payload.split('^'),raw:text};}
function schemaFingerprint(fields){const count=Array.isArray(fields)?fields.length:0;return `fields:${count}`;}
function validateFrame(raw,registry={}){const parsed=splitFrame(raw);if(!parsed.ok)return {...parsed,status:'QUARANTINED'};const schema=registry[parsed.trId];if(!schema)return {...parsed,status:'QUARANTINED',error:'UNKNOWN_SCHEMA',schemaId:null,fieldCount:parsed.fields.length,fingerprint:schemaFingerprint(parsed.fields)};const expected=Number(schema.fieldCount);if(!Number.isInteger(expected)||expected<=0||parsed.fields.length!==expected)return {...parsed,status:'QUARANTINED',error:'FIELD_COUNT_MISMATCH',schemaId:schema.schemaId||parsed.trId,expectedFieldCount:expected,fieldCount:parsed.fields.length,fingerprint:schemaFingerprint(parsed.fields)};return {...parsed,status:'VALID',schemaId:schema.schemaId||parsed.trId,fieldCount:parsed.fields.length,fingerprint:schemaFingerprint(parsed.fields)};}
function captureEnvelope(raw,receivedAt,registry={}){const checked=validateFrame(raw,registry);return {receivedAt,rawFrame:String(raw||''),trId:checked.trId||'',dataCount:Number.isInteger(checked.dataCount)?checked.dataCount:null,rawPayload:checked.payload||'',status:checked.status,error:checked.error||null,schemaId:checked.schemaId||null,fieldCount:checked.fieldCount??null,fingerprint:checked.fingerprint||null};}
function sessionBoundaryProbe(symbol,frames,registry={}){return (frames||[]).map(item=>({symbol:String(symbol||''),...captureEnvelope(item.raw,item.receivedAt,registry)}));}
const api={TR,splitFrame,schemaFingerprint,validateFrame,captureEnvelope,sessionBoundaryProbe};if(typeof module!=='undefined'&&module.exports)module.exports=api;global.MarketBriefingKisWire=api;
})(typeof globalThis!=='undefined'?globalThis:this);
